language: node_js
node_js:
  - lts/*
  - node
services:
  - postgresql
before_install:
  - psql -c "ALTER USER postgres PASSWORD 'postgres';" -U postgres
install:
  - yarn install
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn demo:build
  - yarn test:cov
after_success:
  - yarn cov:merge
  - yarn coveralls
